server {
    listen 3000;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Fallback to index.html for Single Page Applications (React Router)
        try_files $uri $uri/ /index.html;
    }
}
